version: 0.0.{build}

platform: Any CPU

matrix:
  allow_failures:
  - platform: x86
  - version: latest

branches:
  only:
    - master

configuration: 
  - Debug
  - Release
  
  
notifications:
  - provider: Email
    to:
     - '{{commitAuthorEmail}}'
     - ...
    on_build_failure: true 

build:
  verbosity: minimal
