version: 0.0.{build}

platform:
  - x86
  - x64

matrix:
  allow_failures:
  - platform: x86
  - version: latest

branches:
  only:
    - master

configuration: 
  - Debug
  - Release
  
  
notifications:
  - provider: Email
    to:
     - '{{commitAuthorEmail}}'
     - ...
    on_build_failure: true 

build:
  parallel: true
  project: Game Engine 2D.sln

  verbosity: minimal
