version: 0.4.{build}

branches:
  only:
    - master
    - Front-End

configuration: 
  - Debug
  - Release

platform: 
  - x86
  - x64

notifications:
  - provider: Email
    to:
     - '{{commitAuthorEmail}}'
    on_build_failure: true 
    on_build_success: false 
    on_build_status_changed: false 

build:
  parallel: true
  project: Square Up.sln

  verbosity: normal

test:
  assemblies:
    only:
      - SDL2_ttf.lib
