version: 0.0.{build}

branches:
  only:
    - master

configuration: 
  - Debug
  - Release
  
notifications:
  - provider: Email
    to:
     - '{{commitAuthorEmail}}'
     - ...
    on_build_failure: true 
    on_build_success: false 
    on_build_status_changed: false 

build:
  parallel: true
  project: Square Up.sln

  verbosity: minimal
