version: 0.0.{build}

branches:
  only:
    - master

configuration: 
  - Debug
  - Release
  
  
notifications:
   - provider: Email
   - to:
   - '{{commitAuthorEmail}}'
   ...
   on_build_failure: true

build:
  verbosity: minimal
  
